# My Gists

This README would normally document whatever steps are necessary to get the
application up and running.

. Ruby version: *2.5.0*
. Uses https://github.com/jneen/rouge[rouge gem] –
  a pure-ruby code highlighter that is compatible with _pygments_.
. https://www.railstutorial.org/book/beginning#sec-deploying[Deployment instructions for Heroku]
  by M. Hartl
. http://edgeguides.rubyonrails.org/getting_started.html#adding-a-second-model[Adding a Second Model].
Kod jest na gałęzi _add_comments_
+
```sh
git checkout add_comments
```

## Adding a second model

The second model will handle comments on gists.

### 6.1 Generating a Model

```sh
bin/rails generate model Comment commenter:string body:text gist:references
# check generated files models/comments.rb and migration
bin/rails db:migrate
```

### 6.2 Associating Models

* Each comment belongs to one gist.
* One gist can have many comments.

```ruby
class Gist < ApplicationRecord
  has_many :comments
  validates :src, presence: true, length: { minimum: 8, maximum: 256 }
end
```

### 6.3 Adding a Route for Comments

Update _config/routes.rb_.

```ruby
resources :gist do
  resources :comments
end
```

Check routing.

```sh
rails routes
```

### 6.4 Generating a Controller

```ruby
bin/rails generate controller Comments
```

Users will create their comments directly after reading the gist, and once
they have added their comment, will be sent back to the gist show page to see
their comment now listed.

_CommentsController_ is there to provide a method to create comments and
delete spam comments when they arrive.

First update the _Gist_ show template.

```html
<h2>Add a comment</h2>
<%= form_for([@gist, @gist.comments.build]) do |f| %>
  <p><%= f.label :commenter %><br><%= f.text_field :commenter %></p>
  <p><%= f.label :body %><br><%= f.text_area :body %></p>
  <p><%= f.submit %></p>
<% end %>
```

Now, wire up the create in _comments_controller.rb_.

```ruby
class CommentsController < ApplicationController
  def create
    @gist = Gist.find(params[:gist_id])
    @comment = @gist.comments.create(comment_params)
    redirect_to gist_path(@gist)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end
```

Update one more _Gist_ show template.

```html
<% @gist.comments.each do |comment| %>
  <p><strong>Commenter:</strong><%= comment.commenter %></p>
  <p><strong>Comment:</strong><%= comment.body %></p>
<% end %>
```





## From the beginning

[source,bash]
----
rails new my_gists_5.2
cd my_gists_5.2
# bundle install
# bundle install --local
bundle install --without production
# bundle install --without production --local
# bundle --path vendor/bundle --without production
# bundle --path /tmp/<unique id> --without production  # w laboratoriach (quota)
rails server --help
# rails server -p 3000 -b 0.0.0.0
rails server
----

Generate Gist model/views/controlers:

[source,bash]
----
rails generate --help
rails generate scaffold gist src:text lang:string desc:string
# rails db:migrate RAILS_ENV=development
rails db:migrate
# check available routes
# rails routes
# open http://localhost:3000/gists
----

You can have the root of your site routed with "root"

.config/routes.rb
[source,ruby]
----
root 'gists#index'
# http://localhost:3000
----

## Deploying to production – Heroku

Zobacz też https://www.railstutorial.org/book/beginning#sec-deploying[Deploying].

IMPORTANT: W pliku _Gemfile_ należy przenieść
gem _sqlite3_ do grupy _:development, :test_,
a gem _pg_ należy wpisać do grupy _:production_.

[source,ruby]
.Gemfile
----
group :development, :test do
  gem 'byebug', platform: :mri
  gem 'sqlite3'
end

group :production do
  gem 'pg', '1.0.0'
end
----

Teraz czas na instalację https://toolbelt.heroku.com[Heroku Toolbelt].
Po instalacji wykonujemy:

[source,bash]
----
bundle install --without production
git commit -am "Update for Heroku"

# wykonujemy tylko raz
heroku login
heroku keys:add
----

Dodajemy nową aplikację na https://dashboard.heroku.com/apps[Dashboard] albo
dodajemy ją na konsoli.

[source,bash]
----
heroku create
# Creating app... done, ⬢ still-falls-28867
# https://still-falls-28867.herokuapp.com/ | https://git.heroku.com/still-falls-28867.git

heroku apps:rename gists52
# Renaming shrouded-spire-21039 to gists52... done
# https://gists52.herokuapp.com/ | https://git.heroku.com/gists52.git
# Git remote heroku updated
#  ▸    Don't forget to update git remotes for all other local checkouts of the app.
----

Deploying,
zob. też https://devcenter.heroku.com/articles/git[Deploying with Git].

[source,bash]
----
git push heroku master
# remote: Compressing source files... done.
# remote: Building source:
# remote:
# remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
# remote: 			Detected buildpacks: Ruby,Node.js
# remote: 			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
# remote: -----> Ruby app detected
# remote: -----> Compiling Ruby/Rails
# remote: -----> Using Ruby version: ruby-2.5.0
# remote: -----> Installing dependencies using bundler 1.15.2
# remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
# remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

heroku run rails db:migrate
Running rails db:migrate on ⬢ gists52... up, run.1540 (Free)
# MacOS
# heroku open https://gists52.herokuapp.com/
----

Ostrzeżenia (nie pokazane powyżej) powyżej sugeruje, że warto dodać plik _Procfile_:
[source,ruby]
.Procfile
----
web: bundle exec puma -C config/puma.rb
----
oraz uaktualnić gem Bundler do versji 1.16:
[source,ruby]
.Gemfile
----
gem 'bundler', '~>1.16.1'
----
[source,sh]
.Terminal
----
heroku run gem install bundler
----


## Source code prettyprinting

._Gemfile_
[source,ruby]
----
gem 'rouge', '~> 3.1.1'
----

W pliku _app/views/gists/index.html.erb_ wymieniamy element _table_
na element _pre_ i kilka akapitów _p_.

[source,html]
.app/views/gists/index.html.erb
----
<% @gists.each do |gist| %>
  <pre><%= gist.src %></pre>
  <p>Lang: <%= gist.lang %></p>
  <p>Desc: <%= gist.desc %></p>
  <p>
    <%= link_to 'Show', gist %> |
    <%= link_to 'Edit', edit_gist_path(gist) %> |
    <%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>
----

W pliku _app/views/gists/show.html.erb_ podmieniamy element z `@gist.src` na:
[source,html]
.app/views/gists/show.html.erb
----
<pre class="highlight"><%= raw Rouge.highlight @gist.src, @gist.lang, 'html' %></pre>
----

Tworzymy nowy plik _app/assets/stylesheets/rouge.css.erb_ o zawartości:
.app/assets/stylesheets/rouge.css.erb
[source,erb]
----
<%= Rouge::Themes::Github.render(scope: '.highlight')%>
----


## Custom layout with Bootstrap

TODO: Bootstrap 4.

. https://github.com/bootstrap-ruby/bootstrap_form[bootstrap_form].

Co to jest layout? layout aplikacji? gdzie definiujemy layout?

. http://getbootstrap.com[Bootstrap] –
  the most popular HTML, CSS, and JS framework for developing responsive,
  mobile first projects on the web
. https://www.railstutorial.org/book/filling_in_the_layout#sec-custom_css[Bootstrap and custom CSS]
. https://github.com/bootstrap-ruby/rails-bootstrap-forms[rails-bootstrap-forms] –
  a Rails form builder that makes it super easy to create beautiful-looking
  forms with Twitter Bootstrap 3+. Wraps the standard Rails form helpers
  so it’s practically a drop-in replacement.

[source,ruby]
.Gemfile
----
# Make all the necessary Bootstrap files available to the current application
gem 'bootstrap-sass', '3.3.7'
gem 'bootstrap-sass-extras', '0.0.7'

# Optionally install
group :development do
  gem 'rubocop', require: false # for Atom editor
  gem 'scss_lint', require: false # for Atom editor
end
----

Po tych poprawkach w pliku _Gemfile_ wykonujemy na konsoli te polecenia:

[source,sh]
----
bundle
rails generate
rails generate bootstrap:install
rails generate bootstrap:themed gists # <- liczba mnoga!
----


### Bootstrap krok po kroku

Dodajemy pionowy odstęp u góry każdej strony _app/assets/stylesheets/custom.css.scss_:
[source,scss]
----
@import 'bootstrap-sprockets';
@import 'bootstrap';
// body {
//   padding-top: 60px;
// }
----

Zmieniamy layout aplikacji _app/views/layouts/application.html.erb_:
[source,html]
----
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
----

Dodajemy widok częściowy _app/views/layouts/_header.html.erb_:
[source,html]
----
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  '/' %></li>
        <li><%= link_to "About", '/about' %></li>
      </ul>
    </nav>
  </div>
</header>
----

Pozostaje **przywrócić** kolorowanie fragmentów kodu (gists),
dodać podstronę _About_, poprawić _index.html.erb_, itd.
