# https://gists52.herokuapp.com/[My Gists 5.2 with Bootstrap 4]
:toc!:

* https://github.com/RailsApps/rails-bootstrap[Rails 5.1 starter app with the Bootstrap 4 front-end framework].


## Custom layout with Bootstrap 4

[NOTE]
====
*Co to jest layout? Co to jest layout aplikacji?* +
*Gdzie jest zdefiniowany layout aplikacji Rails?*
====

. http://getbootstrap.com[Bootstrap] –
  the most popular HTML, CSS, and JS framework for developing responsive,
  mobile first projects on the web
. https://www.railstutorial.org/book/filling_in_the_layout#sec-custom_css[Bootstrap 3 and custom CSS]
. https://github.com/twbs/bootstrap-rubygem[Bootstrap 4 Ruby Gem for Rails / Sprockets and Compass].


## Bootstrapped layout

Dodajemy dwa gemy do pliku _Gemfile_:
[source,ruby]
.Gemfile
----
gem 'jquery-rails', '~> 4.3.1' # only for Rails >= 5.1
gem 'bootstrap', '~> 4.0.0'
----

Importujemy (S)CSS i dodajemy pionowy odstęp u góry każdej strony:
[source,scss]
.app/assets/stylesheets/application.scss
----
@import 'rouge';
@import 'bootstrap';
@import 'rails_bootstrap_forms';

body {
  padding-top: 60px;
}
----

Zmieniamy layout aplikacji:
[source,html]
.app/views/layouts/application.html.erb
----
<body>
  <div role="main" class="container">
    <%= yield %>
  </div>
</body>
----

Dodajemy widoki częściowe:  *_navigation.html.erb*, *_messages.html.erb*.

Pozostaje jeszcze **przywrócić** kolorowanie fragmentów kodu,
dodać strony z nagłówka strony. Uff! I to chyba wszystko…
czy o czymś jeszcze zapomnieliśmy?


## Bootstrapped forms

. https://github.com/bootstrap-ruby/bootstrap_form[bootstrap_form].
