# https://gists52.herokuapp.com/[My Gists 5.2 with Comments]
:toc!:

The second model will handle comments on gists.

Wzorujemy się na http://edgeguides.rubyonrails.org/getting_started.html[Getting Started with Rails],
sekcje 6, 7 i 8.


### 6.1 Generating a Model

[source,sh]
----
bin/rails generate model Comment commenter:string body:text gist:references
----
Browse generated files:
[source,sh]
----
rougify db/migrate/2018*_create_comments.rb
rougify app/models/comment.rb
----
And run migration:
[source,sh]
----
bin/rails db:migrate
----


### 6.2 Associating Models

* Each comment belongs to one gist.
* One gist can have many comments.

[source,ruby]
.app/models/gist.rb
----
class Gist < ApplicationRecord
  has_many :comments

  validates :src, presence: true, length: { minimum: 8, maximum: 256 }
  validates :lang, presence: true, length: { maximum: 16 }
end
----


### 6.3 Adding a Route for Comments

Update _config/routes.rb_.

[source,ruby]
----
resources :gists do
  resources :comments
end
----
Check routing.
```sh
bin/rails routes
```

*Jak sprawdzić, że wygenerowany/dodany powyżej kod działa?*


### 6.4 Generating a Controller

[source,ruby]
----
bin/rails generate controller Comments
----

Browse generated controller:
[source,sh]
----
rougify app/controllers/comments_controller.rb
----

Users will create their comments directly after reading the gist, and once
they have added their comment, will be sent back to the gist show page to see
their comment now listed.

_CommentsController_ is there to provide a method to create comments and
delete spam comments when they arrive.

First update the Gist show template.
[source,html]
.app/views/gists/show.html.erb
----
<h2>Add a comment</h2>
<%= form_with(model: [@gist, @gist.comments.build], local: true) do |form| %>
  <p><%= form.label :commenter %>: <%= form.text_field :commenter %></p>
  <p><%= form.label :body %>: <%= form.text_area :body %></p>
  <p><%= form.submit %></p>
<% end %>
----

Now, wire up the create in _comments_controller.rb_.
[source,ruby]
.app/controllers/comments_controller.rb
----
class CommentsController < ApplicationController
  def create
    @gist = Gist.find(params[:gist_id])
    @comment = @gist.comments.create(comment_params)
    redirect_to gist_path(@gist)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end
----

Finally, update _Gist_ show template again.
[source,html]
.app/views/gists/show.html.erb
----
<h2>Comments</h2>
<% @gist.comments.each do |comment| %>
  <p><strong>Commenter:</strong> <%= comment.commenter %></p>
  <p><strong>Comment:</strong> <%= comment.body %></p>
<% end %>
----


### 7. Refactoring

- [ ] 7.1 Rendering Partial Collections
- [ ] 7.2 Rendering a Partial Form


### 8 Deleting Comments

- [ ] 8.1 Deleting Associated Objects
