# https://gists52.herokuapp.com/[My Gists 5.2 with Bootstrap 4]
:toc!:

* https://github.com/RailsApps/rails-bootstrap[Rails 5.1 starter app with the Bootstrap 4 front-end framework].


## Custom layout with Bootstrap 4

. http://getbootstrap.com[Bootstrap] –
  the most popular HTML, CSS, and JS framework for developing responsive,
  mobile first projects on the web
. https://www.railstutorial.org/book/filling_in_the_layout#sec-custom_css[Bootstrap 3 and custom CSS]

[NOTE]
====
Co to jest layout? Co to jest layout aplikacji? gdzie jest zdefiniowany layout?
====

. https://github.com/twbs/bootstrap-rubygem[Bootstrap 4 Ruby Gem for Rails / Sprockets and Compass].

Dodajemy potrzebne gemy do _Gemfile_:
[source,ruby]
.Gemfile
----
gem 'jquery-rails', '~> 4.3.1' # for Rails >= 5.1
gem 'bootstrap', '~> 4.0.0'
----

## Bootstrapped forms

. https://github.com/bootstrap-ruby/bootstrap_form[bootstrap_form].






### TODO: Bootstrap 4 krok po kroku

Dodajemy pionowy odstęp u góry każdej strony _app/assets/stylesheets/custom.css.scss_:
[source,scss]
----
@import 'rouge';
@import 'bootstrap-sprockets';
@import 'bootstrap';

body {
  padding-top: 60px;
}
----

Zmieniamy layout aplikacji _app/views/layouts/application.html.erb_:
[source,html]
----
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
----

Dodajemy widok częściowy _app/views/layouts/_header.html.erb_:
[source,html]
----
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  '/' %></li>
        <li><%= link_to "About", '/about' %></li>
      </ul>
    </nav>
  </div>
</header>
----

Pozostaje **przywrócić** kolorowanie fragmentów kodu (gists),
dodać podstronę _About_, poprawić _index.html.erb_, itd.
