# https://gists52.herokuapp.com/[My Gists 5.2 on Heroku]
:toc!:

[NOTE]
====
1. The *bootstrap4* branch contains the version which uses
the https://getbootstrap.com[Bootstrap] toolkit in views.
1. The *adding_second_model* branch contains the version which handles
comments on gists.
====

The README would normally document whatever steps are necessary
to get the application up and running. This README is special.


## Basic info about the app

. Uses Ruby on Rails *5.2.0.rc1* and Ruby version: *2.5.0*.
. https://github.com/jneen/rouge[Rouge] gem is used to highlight code snippets.
. https://gists52.herokuapp.com[The app] is deployed to
  https://www.heroku.com/home[Heroku];
  see https://www.railstutorial.org/book/beginning#sec-deploying[Deployment instructions for Heroku]
  in https://www.railstutorial.org/book/frontmatter[Ruby on Rails Tutorial] by M. Hartl


## Building the app in baby steps

[source,bash]
----
rails new my_gists_5.2
cd my_gists_5.2
bin/bundle install --without production
# bin/bundle install --without production --local
# bin/bundle install --without production --path vendor/bundle

bin/rails server --help
bin/rails server
# rails server -p 3000 -b 0.0.0.0
----

Generate Gist model/views/controlers:

[source,bash]
----
bin/rails generate --help
bin/rails generate scaffold gist src:text lang:string desc:string
bin/rails db:migrate
# rails db:migrate RAILS_ENV=development

bin/rails routes
# open http://localhost:3000/gists
----

You can have the root of your site routed with "root"
[source,ruby]
.config/routes.rb
----
root 'gists#index'
# http://localhost:3000
----

## Deploying to production – Heroku

Zobacz też https://www.railstutorial.org/book/beginning#sec-deploying[Deploying].

[IMPORTANT]
W pliku _Gemfile_ należy przenieść
gem _sqlite3_ do grupy _:development, :test_,
a gem _pg_ należy wpisać do grupy _:production_.

[source,ruby]
.Gemfile
----
group :development, :test do
  gem 'byebug', platform: :mri
  gem 'sqlite3'
end
group :production do
  gem 'pg', '1.0.0'
end
----

Teraz czas na instalację https://toolbelt.heroku.com[Heroku Toolbelt].
Po instalacji wykonujemy:

[source,bash]
----
bin/bundle install --without production
git commit -am "Update for Heroku"

# Te polecenia wykonujemy tylko raz.
heroku login
heroku keys:add
----

Dodajemy nową aplikację na https://dashboard.heroku.com/apps[Dashboard] albo
dodajemy ją na konsoli.

[source,bash]
----
heroku create
# Creating app... done, ⬢ still-falls-28867
# https://still-falls-28867.herokuapp.com/ | https://git.heroku.com/still-falls-28867.git

heroku apps:rename gists52
# Renaming shrouded-spire-21039 to gists52... done
# https://gists52.herokuapp.com/ | https://git.heroku.com/gists52.git
# Git remote heroku updated
#  ▸    Don't forget to update git remotes for all other local checkouts of the app.
----

Zobacz też na Heroku https://devcenter.heroku.com/articles/git[Deploying with Git].

[source,bash]
----
git push heroku master
# remote: Compressing source files... done.
# remote: Building source:
# remote:
# remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
# remote: 			Detected buildpacks: Ruby,Node.js
# remote: 			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
# remote: -----> Ruby app detected
# remote: -----> Compiling Ruby/Rails
# remote: -----> Using Ruby version: ruby-2.5.0
# remote: -----> Installing dependencies using bundler 1.15.2
# remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
# remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

heroku run rails db:migrate
# Running rails db:migrate on ⬢ gists52... up, run.1540 (Free)
# MacOS
# heroku open https://gists52.herokuapp.com/
----

Ostrzeżenia (nie pokazane powyżej) powyżej sugeruje, że warto dodać plik _Procfile_:
[source,ruby]
.Procfile
----
web: bundle exec puma -C config/puma.rb
----


## Source Code Prettyprinting

[source,ruby]
.Gemfile
----
gem 'rouge', '~> 3.1.1'
----

W pliku _app/views/gists/index.html.erb_ wymieniamy element _table_
na element _pre_ i kilka akapitów _p_.

[source,html]
.app/views/gists/index.html.erb
----
<% @gists.each do |gist| %>
  <pre><%= gist.src %></pre>
  <p>Lang: <%= gist.lang %></p>
  <p>Desc: <%= gist.desc %></p>
  <p>
    <%= link_to 'Show', gist %> |
    <%= link_to 'Edit', edit_gist_path(gist) %> |
    <%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>
----

W widoku _show_ podmieniamy element z `@gist.src` na:
[source,html]
.app/views/gists/show.html.erb
----
<pre class="highlight"><%= raw Rouge.highlight @gist.src, @gist.lang, 'html' %></pre>
----

Tworzymy nowy plik _rouge.css.erb_ o zawartości:
.app/assets/stylesheets/rouge.css.erb
[source,erb]
----
<%= Rouge::Themes::Github.render(scope: '.highlight')%>
----
