# https://gists52.herokuapp.com/[My Gists 5.2 with Bootstrap 4]
:toc!:

## Custom layout with Bootstrap

TODO: Bootstrap 4.

. https://github.com/bootstrap-ruby/bootstrap_form[bootstrap_form].

Co to jest layout? layout aplikacji? gdzie definiujemy layout?

. http://getbootstrap.com[Bootstrap] –
  the most popular HTML, CSS, and JS framework for developing responsive,
  mobile first projects on the web
. https://www.railstutorial.org/book/filling_in_the_layout#sec-custom_css[Bootstrap and custom CSS]
. https://github.com/bootstrap-ruby/rails-bootstrap-forms[rails-bootstrap-forms] –
  a Rails form builder that makes it super easy to create beautiful-looking
  forms with Twitter Bootstrap 3+. Wraps the standard Rails form helpers
  so it’s practically a drop-in replacement.

[source,ruby]
.Gemfile
----
# Make all the necessary Bootstrap files available to the current application
gem 'bootstrap-sass', '3.3.7'
gem 'bootstrap-sass-extras', '0.0.7'

# Optionally install
group :development do
  gem 'rubocop', require: false # for Atom editor
  gem 'scss_lint', require: false # for Atom editor
end
----

Po tych poprawkach w pliku _Gemfile_ wykonujemy na konsoli te polecenia:

[source,sh]
----
bundle
rails generate
rails generate bootstrap:install
rails generate bootstrap:themed gists # <- liczba mnoga!
----


### Bootstrap krok po kroku

Dodajemy pionowy odstęp u góry każdej strony _app/assets/stylesheets/custom.css.scss_:
[source,scss]
----
@import 'bootstrap-sprockets';
@import 'bootstrap';
// body {
//   padding-top: 60px;
// }
----

Zmieniamy layout aplikacji _app/views/layouts/application.html.erb_:
[source,html]
----
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
----

Dodajemy widok częściowy _app/views/layouts/_header.html.erb_:
[source,html]
----
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  '/' %></li>
        <li><%= link_to "About", '/about' %></li>
      </ul>
    </nav>
  </div>
</header>
----

Pozostaje **przywrócić** kolorowanie fragmentów kodu (gists),
dodać podstronę _About_, poprawić _index.html.erb_, itd.
